
site_name: DSG_LIB
# Project information
site_name: 'DSG_LIB'
site_description: 'Common functions for Python applications. This is to increase reusability and limit rewritting the same functions in multiple applications. It also allows for defects to be addressed quickly and then be propigated across applications.'
site_author: 'Martin Donath'
# site_url: 'https://squidfunk.github.io/mkdocs-material/'
# Repository
repo_name: 'devsetgo/dsg_lib'
repo_url: 'https://github.com/devsetgo/dsg_lib'

# Copyright
copyright: 'Copyright &copy; 2016 - 2020 Mike Ryan'

nav:
    - Introduction: 'index.md'
    # - QuickStart: 'quickstart.md'
    # - FileFunctions: 'file_functions.md'
    # - FolderFunctions: 'folder_functions.md'
    # - RegExFunctions: 'regex.md'
    # - Contributing: 'contribute.md'



# Theme
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'find_replace'
  language: 'en'
  plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - search

extra:
  # feature:
  #   tabs: true
  search:
    language: 'en'
  social:
    - type: 'github'
      link: 'https://github.com/devsetgo'
    - type: 'twitter'
      link: 'https://twitter.com/stuxstu'