site_name: 'Python Project Template'
# Project info
site_name: 'Python Project Tempaltes'
site_description: 'A simple template for common Python projects I make'
site_author: 'Mike Ryan'
# site_url: 'https://squidfunk.github.io/mkdocs-material/'
# Repository
repo_name: 'devsetgo/python-project-template'
repo_url: 'https://github.com/devsetgo/python-project-template'

# Copyright
copyright: 'Copyright &copy; 2016 - 2020 Mike Ryan'

nav:
    - Introduction: 'index.md'
    # - QuickStart: 'quickstart.md'
    # - FileFunctions: 'file_functions.md'
    # - FolderFunctions: 'folder_functions.md'
    # - RegExFunctions: 'regex.md'
    # - Contributing: 'contribute.md'



# Theme
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'find_replace'
  language: 'en'
  plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - search

extra:
  # feature:
  #   tabs: true
  search:
    language: 'en'
  social:
    - type: 'github'
      link: 'https://github.com/devsetgo'
    - type: 'twitter'
      link: 'https://twitter.com/stuxstu'